### PR TITLE
APP-677: Fix compilation errors for swift 5.2

### PR DESCRIPTION
**Pull request by niil-ohlin**
The `noTrailingClosure` trick stopped working for swift 5.2. Remove that and fix the ambiguity. The explicit requirement is only a problem internally in the framework. External code will still be able to use the trailing closure syntax.

### CODE REVIEW

File: Flow/CoreSignal.swift [hunk 1]
```diff
@@ -24,7 +24,7 @@ public final class CoreSignal<Kind: SignalKind, Value> {
     public typealias Event = Flow.Event<Value>
     typealias EventType = Flow.EventType<Value>
 
-    internal init(onEventType: @escaping (@escaping (EventType) -> Void) -> Disposable, _ noTrailingClosure: Void = ()) {
```
Comment (niil-ohlin) [inline Flow/CoreSignal.swift]: This trick stopped working in swift 5.2

Comment (mansbernhardt) [reply Flow/CoreSignal.swift]: What is the compiler complaining about?

Comment (niil-ohlin) [reply Flow/CoreSignal.swift]: The new compiler now allows `init(onEventType:)` to be called with trailing closure syntax. So there was ambiguity between `init(onEventType:)` and `init(onValue:)`

Comment (moglistree) [reply Flow/CoreSignal.swift]: The compiler gives this message:
`Ambiguous use of 'init'`

File: .circleci/config.yml [hunk 2]
```diff
@@ -120,12 +120,18 @@ jobs:
...
+    macos:
+      xcode: "11.4.0"
+    steps:
+      - test_main_project
+
   test-xcode10-ios12:
     macos:
       xcode: "10.3.0"
     steps:
       - test_main_project
```
Comment (moglistree) [inline .circleci/config.yml]: think that this can be cleaned up as well.

File: .circleci/config.yml [hunk 3]
```diff
@@ -120,12 +120,18 @@ jobs:
           path: swiftlint.html
           destination: swiftlint.html
 
+  test-xcode11-4-beta-ios13:
+    macos:
+      xcode: "11.4.0"
+    steps:
+      - test_main_project
```
Comment (moglistree) [inline .circleci/config.yml]: is there a reason for keeping the old runner and not making this the default runner?

**Comment by mansbernhardt** [comment]
@moglistree As it only seems to be internal fixes and I would assume it will still compile with Swift 5.1, then it feels safe to release as a point release.

**Comment by moglistree** [comment]
Yes I have testes swift 4.2, 5.0, 5.1 and its all good
